### ISSUE TITLE
Move ibis-mssql package into upstream feedstock repo

### ISSUE THREAD

**Issue by gforsyth** [conda-forge/ibis-mssql-feedstock#2]
Hey @conda-forge/help-python and @costrouc!

The [`ibis-framework-feedstock` repo](https://github.com/conda-forge/ibis-framework-feedstock/pull/60) now has backend specific packages for various Ibis backends (which is why, I imagine, this feedstock was created in the first place).

If @costrouc is willing can we retire this feedstock and roll the `mssql` backend part into the main feedstock repo?  It's only a few lines on my end to add the `mssql` backend package, but I'm not sure if we need to poke upload permissions to allow for a package upload to come from a new feedstock.

**Comment by xmnlab** [comment]
hey @gforsyth , as far as i know, the recipe there is just for the backends supported directly by ibis.
maybe we could add an extra source url and maybe it would work there

the problem is that, if we want to update ibis-mssql, all the other backends would need to be rebuilt and, in the case one of them is not working for a dependency problem, we cannot have ibis-msql package published until we fix the problem with the other package (or remove it).

so not sure if it is a good idea to move from this feedstock to the upstream one.

do you have anything in mind about this migration?

**Comment by gforsyth** [comment]
Hey @xmnlab -- my brain converted `mssql` into `mysql` when I was looking at this -- you're right, this should not be rolled into the upstream recipe.  Sorry for the noise everyone!

**Comment by xmnlab** [comment]
np, and thanks for sharing your ideas :)
